category = Category.create(title: 'Breath', detail:'Respira')
category_two = Category.create(title: 'Calm Down', detail:'Escuta musica')
category_three = Category.create(title: 'Play', detail:'Brincar com amigos')
activity = Activity.create(category_id:1, name:'breathing with a pinwheel', description:'breathing affect how our mind and bodies feel')
activity_two = Activity.create(category_id:2, name:'count to five ', description:'feel calm and peaceful and take five')
activity_three = Activity.create(category_id:3, name:'airplane ', description:'have fun with your little one and fly away')
